language: python
python: 2.7
branches:
  only:
  - source
install:
- pip install pelican markdown ghp-import
script:
- make publish github

env:
  global:
    secure: "2c2j5ySmFz4VdtPHLZ443ahRP9OZoNlljCmpbWWnfSJL2vZm0YmnWKCPKae8+P/LZHN6KlVvF/QAhW4waILbvqirCniwDtad14VJNiR3yDsKixmLI/sSAPtBRa3hxhrR8zcq6/VA32WYfCvLXp3dpyq44G4SKfVuxdalLtshfAR2n3mqYsCWqVL0tum6FTKgE55zDvM+gIxZTlvLx4GqjMvgMF1fXiddDdNQIbm6OaykeuTe3fIcRtH9iUnmAyuRNTqlAtXt4uJsLBfdaKy2xdqSsXIHKJXEbX6LBQrRR8NxCN4EkTwC3oifpeWajSj6vtHbYGcY00GIuWpXdoNx1jjZgdjPwl9Ki8dumXMu11DCaWj7Rbo5pO3ENBEK+j1ozZhuts/aXXQJvqrcPX1kQ8HhKgaAqIDQg53HrgmO1UYGKQ78OlN86SmeMjBm0AJ1FI62u2H7NRkoM0GFG8QSgnQDcdLYrckbq/nV6sSP51gwbLSOw606Pyg3wzLa9ObW7UWKIkIUi+PFayczJ2p7fRrSZ0PsQVA+TWR/mul6Lj5SQ6eDXVNfVVVXwS6+OXlM8czVYPrahUJ1jSxPBqYbHkg5HkFQWerjlPHcHVmEQbhe2ui3SpxhYUBKnGsao0I+XCyBlKzzrvdlh7zT9xVZCY8uaPY2rYLB5I0YXUO45kA="
#GH_TOKEN=